### PR TITLE
Major refactor

### LINKED ISSUE #321: Major refactor
I'd like to change much of the underlying dependencies of torbrowser-launcher:

* Switch from python2 to python3 (will resolve #214)
* Switch from gtk2 to Qt5 (will resolve #319)
* Switch from twisted to using Qt threads for asynchronous
* Switch from txsocksx to requests/PySocks (will resolve #213)
* ~Switch from pygame (for playing optional .ogg) to pyaudio~ Alas, I think I'm actually just going to remove the modem sound. It was fun, but pygame for python3 isn't packaged, pyaudio doesn't support ogg files, and it's really not necessary anyway

This will make it much easier for me to maintain since I'm more familiar with this stack, and it's always good to switch to newer, actively maintained software.

### PR DESCRIPTION
**Pull request by micahflee**
In this pull request I:

- Switch from python2 to python3
- Switch from gtk2 to Qt5
- Switch from twisted to requests/socks
- Use QThreads for async, and now download, verify, and extract in separate threads too
- Remove modem sound
- Stopped refreshing the gpg keyring each time, and instead only refresh it when you hit a verification error (and then try verifying again before actually displaying the error)
- On verification error, it saves a copy of the tarball and sig that failed to verify
- Improved python style with flake8

This fixes #321, #213, #214, and #319.

### CODE REVIEW

**Comment by intrigeri** [comment]
> @intrigeri I know you're aiming to only focus on the AppArmor part of this project, but would you mind reviewing this PR before I merge it into develop?

It would not be reasonable for me to expand the scope of my commitment on this project. But perhaps Roger Shimizu, the main maintainer of the package in Debian currently, would be happy to do this review?

**Comment by micahflee** [comment]
Good idea, I will contact Roger.

**Comment by troubadoour** [comment]
I forked from `major refactor` branch. (debian stretch in Qubes 4.0).

It does work fine, except for a minor (?) issue. The gui (empty) is showing whatever the state (tbb installed, latest version), and stays open after stopping Tor Browser. A second instance pops when restarting the launcher,  and so on... 

When torbrowser-launcher is started from command line, we have to ctrl-c or close the gui before being able to restart it.

**Comment by rogers0** [comment]
> It does work fine, except for a minor (?) issue. The gui (empty) is showing whatever the state (tbb installed, latest version), and stays open after stopping Tor Browser. A second instance pops when restarting the launcher, and so on...

> When torbrowser-launcher is started from command line, we have to ctrl-c or close the gui before being able to restart it.

@micahflee I can reproduce the issue mentioned.
Please kindly help to fix if possible. Thanks!

**Comment by troubadoour** [comment]
> Please kindly help to fix if possible. Thanks!

Not sure this was addressed to me.

Anyhow, an update in ```__init__.py``` that seems to fix the issue. Could you review?
 
https://github.com/troubadoour/torbrowser-launcher/commit/1402015487db5559847492ca294ac6c895245dca

**Comment by rogers0** [comment]
> troubadoour/torbrowser-launcher@1402015
> troubadoour/torbrowser-launcher@63646cb

@micahflee 
I confirm the problem goes away after applying two patches above.

@troubadoour 
Really appreciated!

**Comment by rogers0** [comment]
@micahflee @troubadoour 
I just uploaded 0.3.0~dev-1~exp2 to debian experimental.
It should hit the archive shortly. After that you can install it if you use debian.

How to install from experimental repo can be referenced:
- https://wiki.debian.org/TorBrowser#Debian_.22experimental.22

After you test it well, and upstream removes ".dev" in the version string, I think I can upload to unstable.

**Pull request merged**
