### PR TITLE
Update Tor Browser Developers public key (#481)

### LINKED ISSUE #481: Update Tor Browser Signing Key
The expiration dates were extended.

### PR DESCRIPTION
**Pull request by sysrqb**
Closes #481

### CODE REVIEW

**Comment by rogers0** [comment]
@sysrqb the key file was previously in text armor, but changed to binary by your patch.
I think you should convert it by command:
```
gpg --enarmor < binary_key.dat > text_key.txt
```

**Comment by rogers0** [comment]
FYI. I uploaded debian package 0.3.2-12 with the patch:
- https://salsa.debian.org/pkg-privacy-team/torbrowser-launcher/-/blob/debian/sid/debian/patches/0028-Update-Tor-Browser-Developers-public-key-481.patch

**Comment by kpcyrd** [comment]
We've also uploaded this patch to Arch Linux with torbrowser-launcher 0.3.2-3:

https://github.com/archlinux/svntogit-community/commit/70c11880e9e3adda8376da8ee31c3921f48c8c62

**Comment by anthraxx** [comment]
This key is 3 MB in size, it should be reduced to just the key and selfsigs

**Comment by eli-schwartz** [comment]
```
BIN +3.3 MB (26000%) share/torbrowser-launcher/tor-browser-developers.asc
```

Do you suppose there's a tiny chance this PR is completely and utterly wrong?

Old file:
https://github.com/micahflee/torbrowser-launcher/blob/275a2b82e3a3ea4027f664ecb7d9472ae4032c25/share/torbrowser-launcher/tor-browser-developers.asc#L1-L210

210 lines (209 sloc) 13.1 KB
file type: PGP public key block Public-Key (old)

New file:

https://github.com/sysrqb/torbrowser-launcher/blob/24811754d600e514ea94cf86f4d225bd9ca05f2a/share/torbrowser-launcher/tor-browser-developers.asc

3.31 MB
file type: PGP/GPG key public ring (v4) created Mon Dec 15 04:54:02 2014 RSA (Encrypt or Sign) 4096 bits MPI=0xd032cf90e5c02c85...

is a non-armored binary (should be .gpg, not .asc) and contains 21310 signatures, most of them poisoned I'm guessing. ;)

**Comment by rogers0** [comment]
@anthraxx @eli-schwartz @kpcyrd 

Thanks for your info!
I successfully stripped the key size to around 200KB:
```
TEMP=temp_gpg
mkdir -p $TEMP
chmod 700 $TEMP
gpg --homedir $TEMP -v --import-filter drop-sig="sig_created_d=2019-06-30" --import new.key
gpg --homedir $TEMP -a --export '4E2C6E8793298290' > share/torbrowser-launcher/tor-browser-developers.asc
rm -rf $TEMP
```

**Comment by eli-schwartz** [comment]
I would actually recommend

```
gpg --homedir <homedir> --export-options export-minimal --export <keyid>
```

export-minimal ensures the exported key only contains the latest self-sig and no other web of trust data (for good or ill). And that's all you need if you trust the key out of band due to embedding it in a software distribution, and merely want to use it for verifying a signature against a known keyid.

You should be able to get it down to about 8 KB.

**Comment by eli-schwartz** [comment]
I also think it makes sense to just stick with the ASCII-armored output type currently in use.

**Comment by rogers0** [comment]
@eli-schwartz thanks!

I updated debian package 0.3.2-13, with the patch (with latest update from this thread):
- https://salsa.debian.org/pkg-privacy-team/torbrowser-launcher/-/blob/debian/sid/debian/patches/0028-Update-Tor-Browser-Developers-public-key-481.patch

**Comment by AsciiWolf** [comment]
I agree that the text armor format would definitely be better. @sysrqb Any chance you could update this PR?

**Comment by sysrqb** [comment]
@AsciiWolf thanks for the suggested command. We're at 8KB now.

```
$ gpg2 --armour --export-options export-minimal --export 0x4E2C6E8793298290 > 0x4E2C6E8793298290.asc
$ du -sh 0x4E2C6E8793298290.asc
8.0K	0x4E2C6E8793298290.asc
$ mv 0x4E2C6E8793298290.asc share/torbrowser-launcher/tor-browser-developers.asc
```

**Comment by micahflee** [comment]
Fixed in #526

**Pull request closed without merging**
