### PR TITLE
AppArmor profiles, 2018-01 edition

### PR DESCRIPTION
**Pull request by intrigeri**
This branch includes:

* some follow-ups to #280 and #294 to make e10s work fine especially with a Linux 4.14 kernel
* silencing all the denial logs I could observe
* support for obfs4 and obfs3
* various updates, refactoring and clean-ups

Applying this upgrade to a running system requires special care, see the notes to packagers in the commit messages, that should IMO be copied to the release notes.

### CODE REVIEW

**Comment by ageis** [comment]
just making a note/reminder, I can help test this branch this weekend. @micahflee

**Comment by ge-fa** [comment]
@intrigeri Thanks for the work on this! Should this be tested?

**Comment by intrigeri** [comment]
> @intrigeri Thanks for the work on this! Should this be tested?

Yes, please :)

**Comment by rogers0** [comment]
@intrigeri I tried the bridge feature, and yes, obfs4 and obfs3 are working after applying your patches. Thank you!

But meek and fte still got the kernel audit error as below.
Could you kindly help to fix these? 
BTW. My testing system is debian stretch.

```
[1296232.653070] audit: type=1400 audit(1521382524.268:121): apparmor="DENIED" operation="exec" profile="torbrowser_tor" name="~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/firefox" pid=26051 comm="meek-client-tor" requested_mask="x" denied_mask="x" fsuid=1000 ouid=1000
[1296832.242735] audit: type=1400 audit(1521383123.883:123): apparmor="DENIED" operation="exec" profile="torbrowser_tor" name="/usr/bin/python2.7" pid=26535 comm="fteproxy.bin" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
```

**Comment by intrigeri** [comment]
Roger Shimizu:
> But meek and fte still got the kernel audit error as below.
> Could you kindly help to fix these? 

I think meek and fte will need much more work so let's file
a dedicated issue and discuss it there, OK?

**Comment by rogers0** [comment]
@intrigeri sure.
Good to know that you're already aware of this.

> support for obfs4 and obfs3

I confirm obfs4 and obfs3 work well after this patchset.
Looking forward to seeing this gets merged.

**Comment by micahflee** [comment]
@intrigeri as we discussed, I've just added you as a collaborator and code owner of `/apparmor/`: https://github.com/micahflee/torbrowser-launcher/commit/0e9db70e1cca2ecfb44dc4687f034d99aa29e204

While it's great to have extra code reviews and testing of the AppArmor profiles, I'm happy with you merging them directly into develop if you think they are ready.

**Comment by intrigeri** [comment]
Micah Lee:
> @intrigeri as we discussed, I've just added you as a collaborator and code owner of `/apparmor/`: https://github.com/micahflee/torbrowser-launcher/commit/0e9db70e1cca2ecfb44dc4687f034d99aa29e204

> While it's great to have extra code reviews and testing of the AppArmor profiles, I'm happy with you merging them directly into develop if you think they are ready.

Excellent, thank you!

**Comment by rogers0** [comment]
@intrigeri 
since the last commit you pushed in this PR
- https://github.com/micahflee/torbrowser-launcher/pull/310/commits/91652b6
We have to amend setup.py a bit.
I have created the patch, enclosed in the commit below:
- https://anonscm.debian.org/git/pkg-privacy/packages/torbrowser-launcher.git/commit/?h=rosh/apparmor&id=ae0070a

I'm not sure how to add the patch after your commits in this PR.
Maybe it's better to start a new PR, after you merge this series.

**Comment by intrigeri** [comment]
Hi @rogers0!

Roger Shimizu:
> since the last commit you pushed in this PR
> - https://github.com/micahflee/torbrowser-launcher/pull/310/commits/91652b6
> We have to amend setup.py a bit.
> I have created the patch, enclosed in the commit below:
> - https://anonscm.debian.org/git/pkg-privacy/packages/torbrowser-launcher.git/commit/?h=rosh/apparmor&id=ae0070a

I'm afraid I don't understand. My PR empties these files, it does not remove them, and the idea is to keep installing them through `setup.py`. Could you please send me details about the FTBFS? I suspect it's caused by some limitation of the packaging tools we use to maintain `debian/patches/` and won't happen once my PR is part of a new upstream release, but that's just a guess.

**Comment by micahflee** [comment]
I'm getting ready to make the 0.3.0 release and I'd love to include these updated AppArmor profiles in it. The `develop` branch has now merged in `major-refactor`.

@rogers0 @intrigeri would you mind checking to make sure this PR works with what's in `develop` and let me know, and then I can merge this into `develop` and make the release?

**Comment by rogers0** [comment]
@intrigeri 
please check the log below.
```
creating <working-dir>/torbrowser-launcher/debian/torbrowser-launcher/etc
creating <working-dir>/torbrowser-launcher/debian/torbrowser-launcher/etc/apparmor.d
copying apparmor/torbrowser.Browser.firefox -> <working-dir>/torbrowser-launcher/debian/torbrowser-launcher/etc/apparmor.d/
copying apparmor/torbrowser.Browser.plugin-container -> <working-dir>/torbrowser-launcher/debian/torbrowser-launcher/etc/apparmor.d/
copying apparmor/torbrowser.Tor.tor -> <working-dir>/torbrowser-launcher/debian/torbrowser-launcher/etc/apparmor.d/
creating <working-dir>/torbrowser-launcher/debian/torbrowser-launcher/etc/apparmor.d/local
error: can't copy 'apparmor/local/torbrowser.Browser.firefox': doesn't exist or not a regular file
```

@micahflee thanks! I'll let you know when I finish.

**Comment by intrigeri** [comment]
> I think the reason is that setup.py simply refuses to copy a null file.

@rogers0 actually when that failure happens the  source file _does not exist_ so `setup.py` cannot copy it. That's because the patch format we use does not allow expressing the distinction between emptying a file and deleting it so when `debian/patches/0015-AppArmor-remove-boilerplate-from-local-override-file.patch` is applied, those files are deleted. So once that patch makes it into an upstream release and the corresponding quilt patch gets removed, it won't cause a FTBFS anymore => case closed. But still, even then I think we'll want to keep `debian/patches/0016-Remove-apparmor-local-path-from-setup.py.patch` (albeit with an updated description): let's not treat these local overrides as conffiles and instead let dh-apparmor manage them.

**Comment by intrigeri** [comment]
> @rogers0 @intrigeri would you mind checking to make sure this PR works with what's in `develop`

@micahflee, tested, it works fine for me.

> and let me know, and then I can merge this into `develop`

Please go ahead (or ask me to merge it myself: apparently I can since
this PR only modifies paths to which I now have commit access to :)

**Pull request merged**
