### PR TITLE
Update available languages for torbrowser

### PR DESCRIPTION
**Pull request by JpegXguy**

### CODE REVIEW

**Comment by rogers0** [comment]
@JpegXguy 
I can only find po for cs hu, which is valid for this pull-request
but I cannot find po for: el es-AR ka lt mk ms ro th

did I miss something?

**Comment by JpegXguy** [comment]
Hi, I'm using the suffixes for the tars found here (for Linux) https://www.torproject.org/download/languages/

I've personally tried it with an "el" locale in my system, and it works. The launcher downloads the el version. It should woth will all of them. So it's no .po files, but tarfiles that are being downloaded, I think

**Comment by rogers0** [comment]
@JpegXguy 
Thanks for your info!
I checked the language list from upstream, and found "my" is missing in your patch.
Could you kindly help to add it as well?

**Comment by JpegXguy** [comment]
Indeed it was missing, I added it in a new commit

**Review by micahflee — APPROVED** [review]

**Pull request merged**
