### PR TITLE
pt_BR translation (.po only)

### PR DESCRIPTION
**Pull request by jjoaovitor7**
+ po/pt_BR.po

### CODE REVIEW

**Comment by rogers0** [comment]
I tried this patch, but after applying locally, I cannot build debian package anymore.
Other po seems fine, but not this one.

Sorry, I don't know much about syntax of po.

**Comment by jjoaovitor7** [comment]
,_,

**Review by micahflee — APPROVED** [review]

**Comment by AsciiWolf** [comment]
@rogers0 Yeah, the po file is broken. Here is a fix: https://github.com/micahflee/torbrowser-launcher/pull/579

**Comment by rogers0** [comment]
@AsciiWolf thanks!
it builds well after your fix.

**Comment by jjoaovitor7** [comment]
@AsciiWolf, thanks for the fix and sorry for this problem.

**Pull request merged**
