### PR TITLE
 AppArmor: sandbox the content rendering processes (e10s) more strictly (Closes: #278)

### PR DESCRIPTION
**Pull request by intrigeri**
I've been using this on my system for a few days, and the (adjusted) version we have in Tails passes our test suite.

### CODE REVIEW

**Comment by intrigeri** [comment]
Hold on, this seems to break downloading files.

**Comment by intrigeri** [comment]
False alert, I was running an older version with a bug that's fixed in this branch. Please review and merge :)

**Comment by intrigeri** [comment]
A month later, here's a gentle ping about this PR :)

**Comment by intrigeri** [comment]
Hi Micah!

Another 1.5 month later: ping? I've now been running Tor Browser with these changes for 2.5 months on my personal system, and didn't notice any regression.

Background: I would love to have this in Tails 3.2, whose code freeze is on September 14, but as usual I would greatly prefer not diverging from upstream :)

**Comment by intrigeri** [comment]
Hold on, this branch will need updates for Linux 4.14. Whenever you're in the mood for reviewing PRs please focus on #290, #291 and #294 first.

**Comment by micahflee** [comment]
Sorry about ignoring this for many, many, months @intrigeri. Can you verify that these these AppArmor changes are still current with Tor Browser 7.5?

**Comment by micahflee** [comment]
I just tested this, along with the other AppArmor PRs, with Tor Browser 7.5 and they all appear to work fine.

**Comment by intrigeri** [comment]
> I just tested this, along with the other AppArmor PRs, with Tor Browser 7.5 and they all appear to work fine.

Strange. As said in https://github.com/micahflee/torbrowser-launcher/pull/280#issuecomment-339634365 I think this branch needed updates especially once the PR for #294 is merged. I'll send a new PR about these updates ASAP.

**Pull request merged**
