### PR TITLE
Update setup.py for python3.8 compatibility

### PR DESCRIPTION
**Pull request by deskos-xp**
modified to enable getting distro for python3.8 while maintaining ability to use python3.7 and below

### CODE REVIEW

**Comment by anthraxx** [comment]
@micahflee ping

**Comment by kpcyrd** [comment]
@micahflee can you have a look at this patch? It's still necessary to build the new torbrowser-launcher 3.3 with python >= 3.8.

@deskos-xp can you rebase your patch?

Thanks!

**Comment by yardenac** [comment]
This patch is still necessary, as setup.py is still using outdated syntax:

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    distro = platform.dist()[0]
AttributeError: module 'platform' has no attribute 'dist'
```

Rebased patch is at https://github.com/yardenac/torbrowser-launcher/commit/5fe206b8fcc31ca6b5df444c2bdcf00c2d81a0d0

**Comment by yardenac** [comment]
On second thought, https://github.com/micahflee/torbrowser-launcher/pull/470 does a better job solving this problem

**Pull request closed without merging**
